# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_MESON) += kvim4n.dtb
dtb-$(CONFIG_ARCH_MESON) += kvim4.dtb
dtb-$(CONFIG_ARCH_MESON) += kvim3.dtb
dtb-$(CONFIG_ARCH_MESON) += kvim3l.dtb
dtb-$(CONFIG_ARCH_MESON) += kvim1s.dtb
